language: node_js
node_js:
  - node

os:
  - linux

dist: xenial

env:
  global:
    - CC_TEST_REPORTER_ID=55357d6baa31d107a84a1dccdcb330216a2ed78e05dcd6f9129931fa8c8a5598

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npx eslint .
  - npm test --coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
